### 서울시 유가 정보 분석

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# file name 합치기
from glob import glob

In [4]:
station_files = glob("./Data/oil/*.xls")

In [5]:
# 파일 이름을 정렬
station_files = sorted(station_files)
station_files

['./Data/oil\\지역_위치별(주유소) (1).xls',
 './Data/oil\\지역_위치별(주유소) (10).xls',
 './Data/oil\\지역_위치별(주유소) (11).xls',
 './Data/oil\\지역_위치별(주유소) (12).xls',
 './Data/oil\\지역_위치별(주유소) (13).xls',
 './Data/oil\\지역_위치별(주유소) (14).xls',
 './Data/oil\\지역_위치별(주유소) (15).xls',
 './Data/oil\\지역_위치별(주유소) (16).xls',
 './Data/oil\\지역_위치별(주유소) (17).xls',
 './Data/oil\\지역_위치별(주유소) (18).xls',
 './Data/oil\\지역_위치별(주유소) (19).xls',
 './Data/oil\\지역_위치별(주유소) (2).xls',
 './Data/oil\\지역_위치별(주유소) (20).xls',
 './Data/oil\\지역_위치별(주유소) (21).xls',
 './Data/oil\\지역_위치별(주유소) (22).xls',
 './Data/oil\\지역_위치별(주유소) (23).xls',
 './Data/oil\\지역_위치별(주유소) (24).xls',
 './Data/oil\\지역_위치별(주유소) (3).xls',
 './Data/oil\\지역_위치별(주유소) (4).xls',
 './Data/oil\\지역_위치별(주유소) (5).xls',
 './Data/oil\\지역_위치별(주유소) (6).xls',
 './Data/oil\\지역_위치별(주유소) (7).xls',
 './Data/oil\\지역_위치별(주유소) (8).xls',
 './Data/oil\\지역_위치별(주유소) (9).xls',
 './Data/oil\\지역_위치별(주유소).xls']

In [6]:
# xls를 읽기 위해
!pip install xlrd

Requirement already satisfied: xlrd in c:\kenny\lib\site-packages (2.0.1)

In [7]:
tmp_raw = []
for file_name in station_files:
  tmp = pd.read_excel(file_name, header=2)
  tmp_raw.append(tmp)

station_raw = pd.concat(tmp_raw)

In [8]:
len(station_raw)

428

In [9]:
station_raw.head()

,지역,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,실내등유
0,서울특별시,구천면주유소,서울 강동구 구천면로 357 (암사동),HD현대오일뱅크,02-441-0536,N,-,1648,1487,-
1,서울특별시,재건에너지 재정제2주유소 고속셀프지점,서울특별시 강동구 천호대로 1246 (둔촌제2동),HD현대오일뱅크,02-487-2030,Y,-,1659,1489,-
2,서울특별시,방아다리주유소,서울 강동구 동남로 811 (명일동),SK에너지,02-442-5145,Y,1875,1675,1495,-
3,서울특별시,sk해뜨는주유소,서울 강동구 상일로 132 (강일동),SK에너지,02-442-7801,Y,1959,1689,1569,1600
4,서울특별시,대성석유(주)길동주유소,서울 강동구 천호대로 1168,GS칼텍스,02-474-7222,N,1895,1696,1578,1500

In [10]:
station_raw.info()

<class 'pandas.core.frame.DataFrame'>
Index: 428 entries, 0 to 29
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지역      428 non-null    object
 1   상호      428 non-null    object
 2   주소      428 non-null    object
 3   상표      428 non-null    object
 4   전화번호    428 non-null    object
 5   셀프여부    428 non-null    object
 6   고급휘발유   428 non-null    object
 7   휘발유     428 non-null    int64
 8   경유      428 non-null    int64
 9   실내등유    428 non-null    object
dtypes: int64(2), object(8)
memory usage: 36.8+ KB

In [11]:
# 필요항목 발췌
stations = pd.DataFrame(
  {
    'Oil_store' : station_raw['상호'],
    '주소' : station_raw['주소'],
    '가격' : station_raw['휘발유'],
    '셀프' : station_raw['셀프여부'],
    '상표' : station_raw['상표']
  }
)
stations.head()

              Oil_store                            주소    가격 셀프        상표
0                구천면주유소         서울 강동구 구천면로 357 (암사동)  1648  N  HD현대오일뱅크
1  재건에너지 재정제2주유소 고속셀프지점  서울특별시 강동구  천호대로 1246 (둔촌제2동)  1659  Y  HD현대오일뱅크
2               방아다리주유소          서울 강동구 동남로 811 (명일동)  1675  Y     SK에너지
3              sk해뜨는주유소         서울 강동구  상일로 132 (강일동)  1689  Y     SK에너지
4          대성석유(주)길동주유소              서울 강동구 천호대로 1168  1696  N     GS칼텍스

In [14]:
# 주소 컬럼에 서울특별시로 입력되어 있는 부분 확인
[region.split()[0] for region in stations['주소']]

['서울',
 '서울특별시',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울특별시',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울특별시',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울특별시',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울특별시',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울시',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울특별시',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울특별시',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울특별시',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울특별시',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울',
 '서울']

In [15]:
# 주소 컬럼에 주소의 앞부분의 unique 확인 
set([region.split()[0] for region in stations['주소']])

{'서울', '서울시', '서울특별시'}

In [13]:
test = "서울 강동구 구천면로 357 (암사동)"
test.split()[0]

'서울'