## 대선 자료 시각화

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
election = pd.read_csv("./Data/election_2022.csv")
election.head()

    광역시도  시군구    선거인수     투표수     이재명     윤석열   심상정
0  서울특별시  종로구  129968  100629   46130   49172  3115
1  서울특별시   중구  111448   84998   38244   42906  2310
2  서울특별시  용산구  199077  152068   60063   85047  4374
3  서울특별시  성동구  252087  197240   84411  103880  5365
4  서울특별시  광진구  303582  235471  109922  113733  7072

In [3]:
election.tail()

        광역시도   시군구    선거인수     투표수     이재명     윤석열    심상정
243     경상남도   산청군   31645   24913    7125   16607    464
244     경상남도   거창군   53049   41399   11963   27254    895
245     경상남도   합천군   39768   31270    6911   22742    511
246  제주특별자치도   제주시  408552  296826  157695  122084  10007
247  제주특별자치도  서귀포시  155802  112823   55435   50930   3591

In [4]:
election.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   광역시도    248 non-null    object
 1   시군구     248 non-null    object
 2   선거인수    248 non-null    int64
 3   투표수     248 non-null    int64
 4   이재명     248 non-null    int64
 5   윤석열     248 non-null    int64
 6   심상정     248 non-null    int64
dtypes: int64(5), object(2)
memory usage: 13.7+ KB

In [5]:
# 기본 통계량 확인하기
election.describe()

,선거인수,투표수,이재명,윤석열,심상정
count,248.000000,248.000000,248.000000,248.000000,248.000000
mean,176570.540323,136147.838710,64479.104839,65566.290323,3215.532258
std,141049.731983,108569.706317,56875.864428,56766.365763,2893.695797
min,8141.000000,6653.000000,1590.000000,2052.000000,109.000000
25%,47671.500000,39215.750000,17363.000000,18223.000000,709.000000
50%,154353.500000,114654.000000,48797.000000,50341.000000,2617.500000
75%,265099.250000,204189.250000,99830.750000,101949.750000,5041.000000
max,703896.000000,542027.000000,285227.000000,275155.000000,13249.000000

In [6]:
# 컬럼명만 확인하기
election.columns

Index(['광역시도', '시군구', '선거인수', '투표수', '이재명', '윤석열', '심상정'], dtype='object')

In [7]:
# Dimension
election.shape

(248, 7)

----

In [12]:
# electionSum에 윤석열 + 이재명 + 심상정 

election['electionSum'] = election[['이재명', '윤석열', '심상정']].sum(axis='columns')
election.head()

    광역시도  시군구    선거인수     투표수     이재명     윤석열   심상정  electionSum
0  서울특별시  종로구  129968  100629   46130   49172  3115        98417
1  서울특별시   중구  111448   84998   38244   42906  2310        83460
2  서울특별시  용산구  199077  152068   60063   85047  4374       149484
3  서울특별시  성동구  252087  197240   84411  103880  5365       193656
4  서울특별시  광진구  303582  235471  109922  113733  7072       230727

In [17]:
# electionSum이 투표수의 몇퍼센트 
election['electionRatio'] = round(election['electionSum'] / election['투표수'] * 100, 2)
election.head()

,광역시도,시군구,선거인수,투표수,이재명,윤석열,심상정,electionSum,electionRatio
0,서울특별시,종로구,129968,100629,46130,49172,3115,98417,97.80
1,서울특별시,중구,111448,84998,38244,42906,2310,83460,98.19
2,서울특별시,용산구,199077,152068,60063,85047,4374,149484,98.30
3,서울특별시,성동구,252087,197240,84411,103880,5365,193656,98.18
4,서울특별시,광진구,303582,235471,109922,113733,7072,230727,97.99

In [18]:
# csv로 저장하기 (election_2022_job.csv)
election.to_csv("./Data/election_2022_job.csv", index=False)